
image: Visual Studio 2019

branches:
  only:
    - dev
    - main    

environment:
  CustomEnvVar1: CustomEnvVar1Value
  CustomEnvVar2: CustomEnvVar2Value

  matrix:
    - job_name: build_dev
      CustomEnvVar1: CustomEnvVar1Value_ChangedBy_job-build_dev

    - job_name: build_main
      CustomEnvVar1: CustomEnvVar1Value_ChangedBy_job-build_main
      CustomEnvVar3: CustomEnvVar3Value_job-build_main

    - job_name: added_node_task_dev
    - job_name: added_node_dependend_task_dev
      job_depends_on: added_node_task_dev

build_script:
  - ps: | 
      Write-Host "General Build script"
      Write-Host "Branch: $env:APPVEYOR_REPO_BRANCH"
      Write-Host "JobName: $env:APPVEYOR_JOB_NAME"
      Write-Host "CustomEnvVar1: $env:CustomEnvVar1"
      Write-Host "CustomEnvVar2: $env:CustomEnvVar2"
      Write-Host "CustomEnvVar3: $env:CustomEnvVar3"
      Write-Host "ProgressPreference = $($ProgressPreference)"
      iwr -uri https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.1%2B12/OpenJDK17U-jdk_x86-32_windows_hotspot_17.0.1_12.zip -outfile .\test.zip
      mkdir .\test
      Expand-Archive -Path .\test.zip -DestinationPath .\test\

test: off  

for:
  -
    matrix:
      only:
        - job_name: build_dev

    branches:
      only:
        - dev

    skip_commits:
      message: /^Added node.*/

  -
    matrix:
      only:
        - job_name: build_main

    branches:
      only:
        - main

    skip_commits:
      message: /^Added node.*/

  -
    matrix:
      only:
        - job_name: added_node_task_dev

    branches:
      only:
        - dev
      
    only_commits:
      message: /^Added node.*/

    build_script:
      - ps: | 
          Write-Host "Added Node  task script"
          Write-Host "Branch: $env:APPVEYOR_REPO_BRANCH"
          Write-Host "JobName: $env:APPVEYOR_JOB_NAME"
          Write-Host "CustomEnvVar1: $env:CustomEnvVar1"
          Write-Host "CustomEnvVar2: $env:CustomEnvVar2"
          Write-Host "CustomEnvVar3: $env:CustomEnvVar3"

  -
    matrix:
      only:
        - job_name: added_node_dependend_task_dev

    branches:
      only:
        - dev

    only_commits:
      message: /^Added node.*/

    build_script:
      - ps: | 
          Write-Host "Added Node dependend task script"
          Write-Host "Branch: $env:APPVEYOR_REPO_BRANCH"
          Write-Host "JobName: $env:APPVEYOR_JOB_NAME"
          Write-Host "CustomEnvVar1: $env:CustomEnvVar1"
          Write-Host "CustomEnvVar2: $env:CustomEnvVar2"
          Write-Host "CustomEnvVar3: $env:CustomEnvVar3"
